<a href="https://colab.research.google.com/github/shriju/numpy/blob/main/13_numpy_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
# create a null vector of size 10 to but the fifth value is 1.
import numpy as np
import pandas as pd

In [2]:
x=np.nan*np.empty(10)
x[4]=1
x

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

In [3]:
#Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.
a,b=map(int, input("enter two numbers:").split())
y=np.random.random((a,b))
print(y)
print(y.mean())


enter two numbers:4 5
[[0.52212389 0.27372387 0.40523306 0.65633852 0.51634238]
 [0.16446069 0.66732755 0.31988378 0.56378035 0.77235158]
 [0.16261858 0.19436658 0.03823241 0.31809709 0.09293814]
 [0.99305656 0.39550153 0.43687478 0.70262675 0.88603551]]
0.45409568005282164


In [4]:
#Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function
def d2arr(a,b):
  x=np.ones((a,b))
  x[1:-1, 1:-1]=0
  return x

d2arr(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
#Create a vector of size 10 with values ranging from 0 to 1, both excluded
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [6]:
#Can you create a identity mattrix of shape (3,4). If yes write code for it
#identity matrix is a square matrix, so shape(3,4) is not possible
print(np.eye((3)))
np.identity(4)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
# Create a 5x5 matrix with row values ranging from 0 to 4
x=np.zeros((5,5))
x+=np.arange(5)
print(x)



[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [8]:
from numpy.lib.scimath import sqrt
#Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as 
#array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type
a=np.random.randint(1,100,(10,2))
p=np.array([2,3])
#print(a)
np.sqrt(np.sum((a-p)**2, axis=1)).astype(int)


array([ 89,  73,  49,  72,  63, 107,  93,  85, 132,  83])

In [9]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
a=np.zeros((6,7,8))
print(a)
np.unravel_index(100, (6,7,8))

[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0

(1, 5, 4)

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

Input Format:

A single line of input containing space separated numbers.

Output Format:

Print the reverse NumPy array with type float.

Example 1:

Input:

1 2 3 4 -8 -10
Output:

[-10.  -8.   4.   3.   2.   1.]

In [10]:
#Q-9: Arrays
x=input("enter the numbers").split()
np.array(x[::-1], dtype=np.float32)

enter the numbers5 4 3 2 -8


array([-8.,  2.,  3.,  4.,  5.], dtype=float32)

-10: Elements count

Count the number of elements of a numpy array.

Example 1:
Input:

np.array([ ])

Output:
elements_count :  0

Example 2:

Input:
np.array([1, 2])

Output:
elements_count :  2

In [11]:
x=np.array([1, 2])
np.size(x)

2

Q-11: Softmax function
Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

In [22]:
def softmax(arr):
  
  if (type(arr) != np.ndarray):
    print('Requires Numpy Array')
  elif arr.ndim > 1:
    print('Requies 1D Array')
  s = np.sum(np.exp(arr))
  return np.exp(arr)/s
  

softmax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))


array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

Q-12: Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

Example 1:

Input:

a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
 
Output:

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Example 2:

Input:

a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 

Output:

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]

In [29]:
def vertical_stack(*args):
  for i in args:
    if type(i) != np.ndarray:
      raise TypeError("Requires Numpy Array")
    return np.vstack(args)
  

a=np.arange(10).reshape(2, -1)
print('a =', a)
b=np.repeat(1,10).reshape(2, -1)
print('b =', b)

vertical_stack(a,b)


a = [[0 1 2 3 4]
 [5 6 7 8 9]]
b = [[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Q-13: Dates

Create a python function named date_array that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: 2022-12-6. The end date should be included and for simplicity, choose dates from a same year.

Example 1:

Input:

date_array(start = '2020-09-15', end = '2020-09-25')

Output:

['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']

In [33]:
from logging import raiseExceptions
def date_array(start: str, end: str):
    if type(start) != str or type(end) != str:
        raise TypeError
        
    total_days_of_month = {"01": 31, "02": 28, "03": 31, "04":30, "05": 31, "06":30, "07":31, "08":31, "09":30, "10": 31, "11":30, "12":31}

    end = end.split("-")
    end_last = int(end[-1]) + 1
    
    # If the next day of end falls in the next month, account for that
    if total_days_of_month[end[-2]] < end_last:
        days_diff = end_last - total_days_of_month[end[-2]]
        end[-1] = f'0{days_diff}' if days_diff< 10 else f'{days_diff}'
        next_month = int(end[-2]) + 1
        end[-2] = f'0{next_month}' if next_month< 10 else f'{next_month}'
    else:
        end[-1] = f'0{end_last}' if end_last < 10 else f'{end_last}'
    end = "-".join(end)
    return np.arange(start, end, dtype="datetime64[D]")    # Use arange() to generate all dates between start and end 
date_array(start = '2020-11-25', end = '2020-11-30')

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='datetime64[D]')

Q-14: Subtract the mean of each row from a matrix.

In [38]:
x=np.random.random((5,4))
print(x)
x.mean(axis=1, keepdims=True)

[[0.66264796 0.41690859 0.51075539 0.90375709]
 [0.99976304 0.40641322 0.59585279 0.49884145]
 [0.17321173 0.54210218 0.13465458 0.77099936]
 [0.30091527 0.72163264 0.66942208 0.08215866]
 [0.1589751  0.02239628 0.44109347 0.97433946]]


array([[0.62351726],
       [0.62521762],
       [0.40524196],
       [0.44353216],
       [0.39920107]])

### `Q-15:` Swap column-1 of array with column-2 in the array.

In [40]:
a=np.arange(9).reshape(3,3)
print(a)
a[:,[0,2,1]]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

Q-16: Replace odd elements in arrays with -1.

In [45]:
a=np.arange(10)
print(a)
a[a%2==1]=-1
a

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Q-17: Given two arrays of same shape make an array of max out of two arrays. (Numpy way)

a=np.array([6,3,1,5,8])

b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]

In [47]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
a[b>a] = b[a<b]
a

array([6, 3, 1, 7, 8])

### `Q-18` Answer below asked questions on given array:

1.   List item
2.   List item


1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [48]:
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[5266, 4385,  142, 7114, 7512],
       [ 969, 4346, 1616, 9468, 4660],
       [2722, 6216, 8025, 2343, 3944],
       [6734, 1265,  468, 4752, 2062],
       [6210,  879, 1278,  515, 9636],
       [5966, 8809, 3404, 8451, 1413],
       [5338, 1827, 2043, 7766, 4014],
       [1567, 7575, 7432, 2671, 7133]])

In [51]:
arr1[:, ::2]

array([[5266,  142, 7512],
       [ 969, 1616, 4660],
       [2722, 8025, 3944],
       [6734,  468, 2062],
       [6210, 1278, 9636],
       [5966, 3404, 1413],
       [5338, 2043, 4014],
       [1567, 7432, 7133]])

In [54]:
print(arr1.max())
print(arr1.min())

9636
142


In [56]:
(arr1-arr1.min())/(arr1.max()-arr1.min())

array([[0.53970929, 0.44691384, 0.        , 0.73435854, 0.77627976],
       [0.08710765, 0.44280598, 0.15525595, 0.98230461, 0.4758795 ],
       [0.27175058, 0.63977249, 0.83031388, 0.23183063, 0.40046345],
       [0.69433326, 0.11828523, 0.03433748, 0.48556983, 0.20223299],
       [0.63914051, 0.07762798, 0.11965452, 0.03928797, 1.        ],
       [0.61344007, 0.91289235, 0.34358542, 0.87518433, 0.13387403],
       [0.54729303, 0.17748051, 0.20023173, 0.80303349, 0.40783653],
       [0.1500948 , 0.78291553, 0.76785338, 0.26637877, 0.73635981]])

### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [61]:
def nthmax(arr, n):
  if n>len(arr):
    raise IndexError('N is way out of limit')
  arr.sort()
  return arr[-n]

nthmax(np.array([12,34,40,7,1,0]), 2)






34

### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [64]:
a = np.array([1,2,3])
print(np.repeat(a,3))
print(np.tile(a,3))
np.hstack([np.repeat(a, 3), np.tile(a, 3)])


[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])