<a href="https://colab.research.google.com/github/shriju/numpy/blob/main/task_15_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


In [1]:
import numpy as np

See examples:
```
arr = 
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [2]:
# code here
arr=np.random.randint(1,100,(4,3))
print(arr)
#1.Sort this matrix. np.sort()
print(np.sort(arr))
#2.Sort this matrix based on values in 2nd column
print(arr[arr[:,1].argsort()])
#3.Sort this matrix based on max value in each row
print(np.array(sorted(arr, key=lambda x: max(x))))
#4.iv. Sort based on elements value
print(np.sort(arr, axis=None).reshape(4,3))



[[21 16 99]
 [14 40  4]
 [76  4  4]
 [ 1 28 57]]
[[16 21 99]
 [ 4 14 40]
 [ 4  4 76]
 [ 1 28 57]]
[[76  4  4]
 [21 16 99]
 [ 1 28 57]
 [14 40  4]]
[[14 40  4]
 [ 1 28 57]
 [76  4  4]
 [21 16 99]]
[[ 1  4  4]
 [ 4 14 16]
 [21 28 40]
 [57 76 99]]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [3]:
# code here
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
print(marks)
#1.Add marks every student of an extra subject in the same array
extra_subject = np.array([41, 87, 72, 36, 92]).reshape(-1,1)
print(extra_subject)
marks=(np.concatenate([marks, extra_subject],axis =1))
print(marks)
#2.Add two new students marks in respective 5 subjects.(one subject added in above task)
# Two extra students record-
rec1 = np.array([77, 83, 98, 95, 89]).reshape(1,-1)
rec2 = np.array([92, 71, 52, 61, 53]).reshape(1,-1)
marks=np.concatenate([marks, rec1, rec2], axis=0)
print(marks)
#3.Add extra column with sum of all subjects(5-subjects) marks
sum_stud=marks.sum(axis=1, keepdims=True)
print(sum_stud)
marks=np.concatenate([marks, sum_stud], axis=1)
print(marks)
#4.Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows
print(np.array(sorted(marks, key=lambda x: x[-1])))






[[13 10  9 33]
 [63 46 90 42]
 [39 76 13 29]
 [82  9 29 78]
 [67 61 59 36]]
[[41]
 [87]
 [72]
 [36]
 [92]]
[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]
[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]
[[106]
 [328]
 [229]
 [234]
 [315]
 [442]
 [329]]
[[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]
[[ 13  10   9  33  41 106]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 63  46  90  42  87 328]
 [ 92  71  52  61  53 329]
 [ 77  83  98  95  89 442]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [4]:
# code here

arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
#1. Row Wise
print(np.unique(arr, axis=0))
#2. Column Wise
print(np.unique(arr, axis=1))

[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [5]:
# code here
arr = np.array([[1,2,3,3,1,1],
               [0,9,1,2,8,8],
               [1,2,3,8,8,8],
               [1,2,3,3,1,1],
               [0,6,1,2,11,7],
               [10,19,14,-2,8,-1]])
np.flip(arr, axis=[0,1])

array([[-1,  8, -2, 14, 19, 10],
       [ 7, 11,  2,  1,  6,  0],
       [ 1,  1,  3,  3,  2,  1],
       [ 8,  8,  8,  3,  2,  1],
       [ 8,  8,  2,  1,  9,  0],
       [ 1,  1,  3,  3,  2,  1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]] 

X = 6
```

In [6]:
# code here

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [7]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [8]:
# code here
np.concatenate([arr1, arr2, arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [17]:
# code here
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
print(arr)
max_element= arr.argmax()
min_element=arr.argmin()
print(arr.max(), arr.min())
arr=np.delete(arr, max_element, axis=1)
arr= np.delete(arr, min_element, axis=1)
print(arr.max(), arr.min())

[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825
  173 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211
  771 270 308 231 952 514 699 702 433 900 373 318 998 265 503 320 230 324
  922 967 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930
  325 729 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528
  395 525 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859
  618 226 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748
  291 194 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207
  883 588]]
998 103
997 117


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [22]:
# code here
arr=np.random.randint(100,1000, 500)
print(arr)
print(np.sort(np.clip(arr, 100, 200)))
np.cumsum(np.sort(np.clip(arr, 100, 200)))

[813 211 398 629 762 889 967 287 113 704 813 196 106 913 607 362 765 117
 475 592 254 474 219 724 164 418 735 784 104 949 877 650 983 421 581 612
 700 823 198 320 184 537 584 312 646 252 923 267 271 349 559 813 420 334
 662 790 598 234 560 709 911 703 110 608 865 227 579 521 893 796 325 715
 237 953 908 111 727 597 209 851 878 814 266 226 943 735 899 213 791 619
 216 984 730 400 930 178 588 753 692 103 712 730 955 273 592 194 555 308
 816 839 692 444 166 481 480 134 833 640 880 452 855 207 952 284 432 901
 279 731 632 309 292 277 920 334 382 271 327 327 666 703 787 581 190 444
 738 651 493 284 378 706 864 512 459 345 636 173 222 466 907 942 583 622
 158 882 766 461 297 402 301 454 352 392 238 735 799 979 846 705 616 481
 305 718 416 671 515 744 471 937 577 858 237 662 355 901 130 127 987 299
 293 365 291 781 327 198 724 980 757 543 978 402 366 507 180 299 883 666
 543 506 470 620 693 411 431 841 573 182 446 545 335 739 685 967 546 945
 384 506 353 266 483 428 654 533 811 771 986 975 55

array([  102,   205,   309,   415,   524,   634,   745,   858,   972,
        1089,  1211,  1338,  1467,  1597,  1730,  1864,  2009,  2156,
        2310,  2466,  2624,  2788,  2953,  3119,  3292,  3470,  3650,
        3832,  4016,  4206,  4396,  4589,  4783,  4979,  5177,  5375,
        5575,  5775,  5975,  6175,  6375,  6575,  6775,  6975,  7175,
        7375,  7575,  7775,  7975,  8175,  8375,  8575,  8775,  8975,
        9175,  9375,  9575,  9775,  9975, 10175, 10375, 10575, 10775,
       10975, 11175, 11375, 11575, 11775, 11975, 12175, 12375, 12575,
       12775, 12975, 13175, 13375, 13575, 13775, 13975, 14175, 14375,
       14575, 14775, 14975, 15175, 15375, 15575, 15775, 15975, 16175,
       16375, 16575, 16775, 16975, 17175, 17375, 17575, 17775, 17975,
       18175, 18375, 18575, 18775, 18975, 19175, 19375, 19575, 19775,
       19975, 20175, 20375, 20575, 20775, 20975, 21175, 21375, 21575,
       21775, 21975, 22175, 22375, 22575, 22775, 22975, 23175, 23375,
       23575, 23775,

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [29]:
# code here
arr=np.random.random(100)
arr=np.around(arr, decimals=3)
print(arr)
print("0th percentile == minimum value of the array: ", (np.percentile(arr, 0) == arr.min()))
print("100th percentile == maximum value of the array: ", (np.percentile(arr, 100) == arr.max()))
print('difference betwen 51th percenile and 50th percentile values =', (np.percentile(arr, 51))- (np.percentile(arr,50)))

[0.437 0.788 0.041 0.032 0.586 0.034 0.952 0.731 0.965 0.772 0.175 0.359
 0.98  0.953 0.156 0.021 0.634 0.665 0.581 0.434 0.166 0.119 0.102 0.346
 0.606 0.303 0.727 0.01  0.33  0.88  0.671 0.812 0.167 0.457 0.603 0.42
 0.779 0.873 0.227 0.867 0.321 0.902 0.72  0.046 0.525 0.327 0.126 0.418
 0.16  0.453 0.878 0.662 0.656 0.503 0.895 0.683 0.369 0.302 0.089 0.806
 0.972 0.986 0.336 0.597 0.878 0.033 0.204 0.482 0.516 0.216 0.765 0.442
 0.3   0.418 0.008 0.266 0.616 0.424 0.611 0.288 0.267 0.217 0.919 0.666
 0.372 0.534 0.15  0.695 0.952 0.445 0.6   0.07  0.194 0.387 0.092 0.106
 0.702 0.476 0.318 0.332]
0th percentile == minimum value of the array:  True
100th percentile == maximum value of the array:  True
difference betwen 51th percenile and 50th percentile values = 0.005420000000000036
